export {
  addQuestionToSpace,
  convertScratchToSpace,
  copyNode,
  createEmptyTrack,
  createThinkingScratch,
  createThinkingSpace,
  createThinkingSpaceFromDoubt,
  deleteNode,
  deleteThinkingScratch,
  deleteThinkingSpace,
  exportSpace,
  feedScratchToTime,
  getSpaceView,
  getThinkingSnapshot,
  linkThinkingNode,
  listThinkingScratch,
  listThinkingSpaces,
  markNodeMisplaced,
  moveNode,
  organizeSpaceApply,
  organizeSpacePreview,
  rebuildSpace,
  replaceThinkingSnapshot,
  setActiveTrack,
  setSpaceStatus,
  updateNodeAnswer,
  updateNodeQuestion,
  updateSpaceBackground,
  updateSpaceRootQuestion,
  updateSpaceStarMapState,
  writeSpaceToTime
} from "@/lib/server/store/thinking-impl";

export type { StarMapStatePatch } from "@/lib/server/store/thinking-impl";
